/*
 * Turns the Great Rewind corner images into frameless pieces for the corners:
 *  - objects and figures are lifted out of their background with Apple's
 *    Vision framework (on-device; scripts/images/cutout.swift, macOS 14+);
 *  - paintings, maps and scenes Vision cannot lift become a torn scrap of
 *    paper with a deckled edge (no frame).
 * Output: public/img/cut/<slot>.webp with alpha, and src/content/cornerCuts.ts.
 *   node scripts/images/cutouts.mjs [--force] [slot…]
 */
import { readdirSync, existsSync, mkdirSync, writeFileSync, readFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { tmpdir } from "node:os";
import sharp from "sharp";

const HERE = fileURLToPath(new URL(".", import.meta.url));
const IMG = `${HERE}../../public/img`;
const OUT = `${IMG}/cut`;
const TMP = `${tmpdir()}/corner-cuts`;
mkdirSync(OUT, { recursive: true });
mkdirSync(TMP, { recursive: true });
const args = process.argv.slice(2);
const force = args.includes("--force");
const only = args.filter((a) => !a.startsWith("--"));
// images that should stay a paper scrap even if Vision finds "something" in them
const KEEP_PAPER = JSON.parse(readFileSync(`${HERE}paper-corners.json`, "utf8"));

const bin = `${TMP}/cutout`;
if (!existsSync(bin)) execFileSync("swiftc", ["-O", `${HERE}cutout.swift`, "-o", bin]);

/** A deckled, slightly irregular paper outline as an SVG mask. */
function tornMask(w, h, seed) {
  let s = seed;
  const rnd = () => ((s = (s * 16807) % 2147483647) / 2147483647);
  const pts = [];
  const edge = (x0, y0, x1, y1, n) => {
    for (let i = 0; i < n; i++) {
      const t = i / n;
      const j = (rnd() - 0.5) * 0.022 * Math.max(w, h);
      const nx = -(y1 - y0);
      const ny = x1 - x0;
      const l = Math.hypot(nx, ny);
      pts.push([x0 + (x1 - x0) * t + (nx / l) * j, y0 + (y1 - y0) * t + (ny / l) * j]);
    }
  };
  const m = 0.03 * Math.min(w, h);
  edge(m, m, w - m, m * 1.4, 60);
  edge(w - m, m * 1.4, w - m * 1.3, h - m, 60);
  edge(w - m * 1.3, h - m, m * 1.2, h - m * 0.8, 60);
  edge(m * 1.2, h - m * 0.8, m, m, 60);
  const d = pts.map(([x, y], i) => `${i ? "L" : "M"}${x.toFixed(1)},${y.toFixed(1)}`).join("") + "Z";
  return Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}"><filter id="b"><feGaussianBlur stdDeviation="0.8"/></filter><path d="${d}" fill="#fff" filter="url(#b)"/></svg>`);
}

const kinds = {};
const slots = readdirSync(IMG)
  .filter((f) => /^corner-.*\.webp$/.test(f))
  .map((f) => f.replace(/\.webp$/, ""))
  .filter((s) => !only.length || only.includes(s));

for (const slot of slots) {
  const out = `${OUT}/${slot}.webp`;
  if (existsSync(out) && !force) {
    kinds[slot] = "keep";
    continue;
  }
  const png = `${TMP}/${slot}.png`;
  const cut = `${TMP}/${slot}-cut.png`;
  await sharp(`${IMG}/${slot}.webp`).png().toFile(png);
  let kind = "paper";
  if (!KEEP_PAPER.includes(slot)) {
    const res = execFileSync(bin, [png, cut]).toString().trim();
    const m = res.match(/^OK ([\d.]+)/);
    const share = m ? Number(m[1]) : 0;
    // a real subject: not a speck, not the whole frame
    if (m && share > 0.05 && share < 0.82) kind = "cut";
    console.log(slot, res);
  }
  if (kind === "cut") {
    await sharp(cut).trim({ threshold: 1 }).resize({ width: 900, height: 900, fit: "inside", withoutEnlargement: true }).webp({ quality: 82, alphaQuality: 90 }).toFile(out);
  } else {
    const { data, info } = await sharp(`${IMG}/${slot}.webp`)
      .resize({ width: 820, height: 820, fit: "inside", withoutEnlargement: true })
      .png()
      .toBuffer({ resolveWithObject: true });
    const { width, height } = info;
    const seed = [...slot].reduce((a, c) => (a * 31 + c.charCodeAt(0)) % 2147483647, 7) || 7;
    await sharp(data)
      .composite([{ input: tornMask(width, height, seed), blend: "dest-in" }])
      .webp({ quality: 82, alphaQuality: 90 })
      .toFile(out);
  }
  kinds[slot] = kind;
}

// keep earlier results for slots not processed this time
const prev = existsSync(`${HERE}corner-kinds.json`) ? JSON.parse(readFileSync(`${HERE}corner-kinds.json`, "utf8")) : {};
for (const [k, v] of Object.entries(kinds)) if (v !== "keep") prev[k] = v;
writeFileSync(`${HERE}corner-kinds.json`, JSON.stringify(prev, null, 1));
writeFileSync(
  `${HERE}../../src/content/cornerCuts.ts`,
  `// Generated by scripts/images/cutouts.mjs. "cut" = subject lifted from its background, "paper" = torn scrap.\nexport const cornerKind: Record<string, "cut" | "paper"> = ${JSON.stringify(prev, null, 2)};\n`,
);
console.log("done", Object.keys(kinds).length);
