/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KyThuatInRouteImport } from './routes/ky-thuat-in'
import { Route as LaBanRouteImport } from './routes/la-ban'
import { Route as ThuocSungRouteImport } from './routes/thuoc-sung'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KyThuatInRoute = KyThuatInRouteImport.update({
  id: '/ky-thuat-in',
  path: '/ky-thuat-in',
  getParentRoute: () => rootRouteImport,
} as any)
const LaBanRoute = LaBanRouteImport.update({
  id: '/la-ban',
  path: '/la-ban',
  getParentRoute: () => rootRouteImport,
} as any)
const ThuocSungRoute = ThuocSungRouteImport.update({
  id: '/thuoc-sung',
  path: '/thuoc-sung',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ky-thuat-in': typeof KyThuatInRoute
  '/la-ban': typeof LaBanRoute
  '/thuoc-sung': typeof ThuocSungRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ky-thuat-in': typeof KyThuatInRoute
  '/la-ban': typeof LaBanRoute
  '/thuoc-sung': typeof ThuocSungRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ky-thuat-in': typeof KyThuatInRoute
  '/la-ban': typeof LaBanRoute
  '/thuoc-sung': typeof ThuocSungRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/ky-thuat-in' | '/la-ban' | '/thuoc-sung'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ky-thuat-in' | '/la-ban' | '/thuoc-sung'
  id: '__root__' | '/' | '/ky-thuat-in' | '/la-ban' | '/thuoc-sung'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KyThuatInRoute: typeof KyThuatInRoute
  LaBanRoute: typeof LaBanRoute
  ThuocSungRoute: typeof ThuocSungRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ky-thuat-in': {
      id: '/ky-thuat-in'
      path: '/ky-thuat-in'
      fullPath: '/ky-thuat-in'
      preLoaderRoute: typeof KyThuatInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/la-ban': {
      id: '/la-ban'
      path: '/la-ban'
      fullPath: '/la-ban'
      preLoaderRoute: typeof LaBanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thuoc-sung': {
      id: '/thuoc-sung'
      path: '/thuoc-sung'
      fullPath: '/thuoc-sung'
      preLoaderRoute: typeof ThuocSungRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KyThuatInRoute: KyThuatInRoute,
  LaBanRoute: LaBanRoute,
  ThuocSungRoute: ThuocSungRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
